version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
    groups:
      all-github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
    groups:
      all-docker-images:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - "automated"
      - "dependencies"
    assignees:
      - "SilverKnightKMA"
    groups:
      all-go-dependencies:
        patterns:
          - "*"
